# This is a basic workflow to help you get started with Actions

name: Need Drink

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: '0,30 2,3,5,6,7,8,9,10 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  notify:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: GitHub Action for WeChat Work
        uses: chf007/action-wechat-work@1.0.5
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: text
          content: 喝水啦
          mentioned_mobile_list: '["@all"]'
